<a href="https://colab.research.google.com/github/shivanshu-web/Mini_Project/blob/main/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [10]:
clean_df=pd.read_csv("/content/laptop_clean_dataset.csv")

In [11]:
clean_df.sample(5)

,Company,TypeName,Inches,Weight,screen_resolution,display_type,processor_speed,processor_brand,processor_type,ssd_storage,hdd_storage,flash_storage,ram,os,Price
1010,Toshiba,Ultrabook,14.0,1.47,1920x1080,Full HD,2.6,Intel,Core i7 6600U,256,0,0,8,windows,91908.000
18,Lenovo,Notebook,15.6,2.2,1920x1080,Full HD,2.4,Intel,Core i3 7100U,0,1TB,0,8,no,26586.720
1242,HP,Notebook,15.6,2.19,1366x768,HD,2.5,Intel,Core i7 6500U,0,1TB,0,6,windows,40705.920
778,HP,Workstation,15.6,3.14,1920x1080,Full HD,2.8,Intel,Core i7 7700HQ,256,0,0,8,windows,110017.872
1015,Toshiba,Notebook,15.6,2.4,1920x1080,Full HD,2.5,Intel,Core i7 6500U,256,0,0,16,windows,75924.000

In [12]:
clean_df.shape

(1243, 15)

In [13]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1243 entries, 0 to 1242
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Company            1243 non-null   object
 1   TypeName           1243 non-null   object
 2   Inches             1243 non-null   float64
 3   Weight             1243 non-null   object
 4   screen_resolution  1243 non-null   object
 5   display_type       1243 non-null   object
 6   processor_speed    1243 non-null   float64
 7   processor_brand    1243 non-null   object
 8   processor_type     1243 non-null   object
 9   ssd_storage        1243 non-null   int64
 10  hdd_storage        1243 non-null   object
 11  flash_storage      1243 non-null   int64
 12  ram                1243 non-null   int64
 13  os                 1243 non-null   object
 14  Price              1243 non-null   float64
dtypes: float64(3), int64(3), object(9)
memory usage: 145.8+ KB

In [14]:
clean_df.isnull().sum().sum()

np.int64(0)

In [15]:
clean_df['Weight'] = pd.to_numeric(clean_df['Weight'], errors='coerce')

In [16]:
clean_df['Weight'].dtype

dtype('float64')

In [17]:
clean_df[['Resolution_Width', 'Resolution_Height']] = (
    clean_df['screen_resolution']
    .str.extract(r'(\d+)\s*[xX]\s*(\d+)')
    .astype(int)
)

In [18]:
clean_df[
    ['screen_resolution', 'Resolution_Width', 'Resolution_Height']
].head()

  screen_resolution  Resolution_Width  Resolution_Height
0         2560x1600              2560               1600
1          1440x900              1440                900
2         1920x1080              1920               1080
3         2880x1800              2880               1800
4         2560x1600              2560               1600

In [19]:
clean_df['hdd_storage'].value_counts(dropna=False)

hdd_storage
0          695
1TB        390
500        123
2TB         31
1TB 1TB      1
32           1
128          1
0TB          1
Name: count, dtype: int64

In [20]:
clean_df['hdd_storage'] = (
    clean_df['hdd_storage']
    .replace({
        '1TB': '1000',
        '2TB': '2000',
        '0TB': '0',
        '1TB 1TB': '2000'
    })
)

clean_df['hdd_storage'] = pd.to_numeric(
    clean_df['hdd_storage'],
    errors='coerce'
)

In [21]:
print(clean_df['hdd_storage'].dtype)
print(clean_df['hdd_storage'].value_counts(dropna=False))

int64
hdd_storage
0       696
1000    390
500     123
2000     32
32        1
128       1
Name: count, dtype: int64

In [22]:
clean_df.describe()

,Inches,Weight,processor_speed,ssd_storage,hdd_storage,flash_storage,ram,Price,Resolution_Width,Resolution_Height
count,1243.000000,1242.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000
mean,15.010218,2.061006,2.304489,172.788415,414.851167,4.492357,8.450523,60631.450094,1900.006436,1073.824618
std,1.448967,0.738233,0.503998,161.330647,519.231793,30.768612,5.116651,37429.117737,493.027552,283.822819
min,9.448819,0.690000,0.900000,0.000000,0.000000,0.000000,2.000000,9270.720000,1366.000000,768.000000
25%,14.000000,1.500000,2.000000,0.000000,0.000000,0.000000,4.000000,32687.280000,1920.000000,1080.000000
50%,15.600000,2.040000,2.500000,180.000000,0.000000,0.000000,8.000000,52693.920000,1920.000000,1080.000000
75%,15.600000,2.320000,2.700000,256.000000,1000.000000,0.000000,8.000000,79813.440000,1920.000000,1080.000000
max,18.400000,11.100000,3.600000,512.000000,2000.000000,512.000000,64.000000,324954.720000,3840.000000,2160.000000

In [23]:
clean_df.select_dtypes('object').describe()

,Company,TypeName,screen_resolution,display_type,processor_brand,processor_type,os
count,1243,1243,1243,1243,1243,1243,1243
unique,18,5,15,4,3,93,6
top,Dell,Notebook,1920x1080,Full HD,Intel,Core i5 7200U,windows
freq,281,711,814,835,1182,186,1075

In [24]:
cat_col=clean_df.select_dtypes('object').columns
num_col=clean_df.select_dtypes('number').columns

In [25]:
cat_col

Index(['Company', 'TypeName', 'screen_resolution', 'display_type',
       'processor_brand', 'processor_type', 'os'],
      dtype='object')

In [26]:
num_col

Index(['Inches', 'Weight', 'processor_speed', 'ssd_storage', 'hdd_storage',
       'flash_storage', 'ram', 'Price', 'Resolution_Width',
       'Resolution_Height'],
      dtype='object')

In [27]:
clean_df.corr(numeric_only=True)["Price"].sort_values(ascending=False)

Price                1.000000
ram                  0.739096
Resolution_Width     0.553224
ssd_storage          0.551168
Resolution_Height    0.549807
processor_speed      0.426237
Weight               0.204236
Inches               0.049907
flash_storage       -0.033705
hdd_storage         -0.096456
Name: Price, dtype: float64

In [ ]:
# sns.scatterplot(x=clean_df["ram"],y=clean_df["Price"])
import matplotlib.pyplot as plt
import seaborn as sns
import math

# Select numerical columns, excluding target
numer_cols = clean_df.select_dtypes(include='number').columns.drop('Price', errors='ignore')

# Create subplots
fig, axes = plt.subplots(
    len(numer_cols), 3,
    figsize=(18, 5 * len(numer_cols))
)

# Handle axes when there is only one numerical feature
axes = axes.reshape(len(numer_cols), 3)

for i, col in enumerate(numer_cols):

    # 1. Histogram
    sns.histplot(data=clean_df, x=col, kde=True, ax=axes[i, 0])
    axes[i, 0].set_title(f'{col} Distribution')

    # 2. Boxplot
    sns.boxplot(data=clean_df, x=col, ax=axes[i, 1])
    axes[i, 1].set_title(f'{col} Boxplot')

    # 3. Scatterplot with Price
    sns.scatterplot(data=clean_df, x=col, y='Price', ax=axes[i, 2])
    axes[i, 2].set_title(f'{col} vs Price')

plt.tight_layout()
plt.show()

In [34]:
clean_df[num_col].skew()

Inches               -0.469638
Weight                2.573849
processor_speed      -0.847626
ssd_storage           0.596116
hdd_storage           0.898123
flash_storage        11.057739
ram                   2.724098
Price                 1.519041
Resolution_Width      2.214152
Resolution_Height     2.122366
dtype: float64

In [35]:
print("Flash Storage:")
print(clean_df['flash_storage'].value_counts(dropna=False).sort_index())

print("\nWeight Summary:")
print(clean_df['Weight'].describe())

print("\nRAM Values:")
print(clean_df['ram'].value_counts(dropna=False).sort_index())

Flash Storage:
flash_storage
0      1175
16        7
32       35
64       12
128       4
256       8
512       2
Name: count, dtype: int64

Weight Summary:
count    1242.000000
mean        2.061006
std         0.738233
min         0.690000
25%         1.500000
50%         2.040000
75%         2.320000
max        11.100000
Name: Weight, dtype: float64

RAM Values:
ram
2      14
4     359
6      34
8     598
12     25
16    192
24      3
32     17
64      1
Name: count, dtype: int64